title: "OB.DAAC Help Hub"
author: "The Ocean Ecology Laboratory at NASA Goddard"
copyright: "2025-2026"
only_build_toc_files: true
execute:
  timeout: -1
  run_in_temp: true
  execute_notebooks: "cache"
  cache: "docs/_cache"
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  baseurl: "https://nasa.github.io/oceandata-notebooks/"
  analytics:
    google_analytics_id: "G-E0VPP0Z29X"
repository:
  url: "https://github.com/nasa/oceandata-notebooks/"
  branch: "main"
  path_to_book: "docs"
sphinx:
  recursive_update: true
  config:
    language: "en"
    nb_merge_streams: true
    nb_execution_raise_on_error: true
    suppress_warnings:
      - "myst.xref_missing"
      - "mystnb.unknown_mime_type"
    html_extra_path:
      - "assets"
    html_theme_options:
      logo:
        image_light: "HelpHub.png"
        image_dark: "HelpHub-dark.png" 
      show_navbar_depth: 2
      collapse_navigation: false
      navigation_depth: 4
      show_toc_level: 2
      secondary_sidebar_items: ["page-toc", "google-translate"]
    templates_path: "_templates"
  local_extensions:
    source_button: "_ext"
