title: "OB.DAAC Help Hub"
author: "The Ocean Ecology Laboratory at NASA Goddard"
only_build_toc_files: true
execute:
  timeout: -1  # no cell timeout
  run_in_temp: true  # no reuse of downloads, etc.
  execute_notebooks: "cache"  # re-use outputs (when none of the code cells change)
  cache: "docs/_cache"
html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: true
  baseurl: "https://nasa.github.io/oceandata-notebooks/"
repository:
  url: "https://github.com/nasa/oceandata-notebooks/"
  branch: main
  path_to_book: docs
sphinx:
  config:
    nb_merge_streams: true # stdout lines combined in output
    suppress_warnings:
      - "myst.xref_missing"
      - "mystnb.unknown_mime_type"
    html_extra_path:
      - "assets"
    html_theme_options:
      logo:
        image_light: "HelpHub.png"
        image_dark: "HelpHub-dark.png" 
      show_navbar_depth: 2
      collapse_navigation: false
      navigation_depth: 4
      show_toc_level: 2
  local_extensions:
    source_button: _ext
