name: Container image
on:
  push:
    paths:
      - .github/workflows/container-image.yml
      - container/**
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/oceandata-jupyterlab
      BUILDX_NO_DEFAULT_ATTESTATIONS: 1
    permissions:
      packages: write
    steps:
      - name: Checkout container files
        uses: actions/checkout@v5
        with:
          sparse-checkout: container
      - name: Repository metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable=true
          labels: |
            org.opencontainers.image.description="environment with JupyterLab for the oceandata-notebooks"
            repo2docker.repo=https://github.com/${{ github.repository }}
            repo2docker.ref=${{ github.ref }}
      - name: Build args
        run: |
          TAGS=($DOCKER_METADATA_OUTPUT_TAGS)
          TAGS=${TAGS[@]/#/--DockerEngine.extra_buildx_build_args=--tag=}
          echo "TAGS=$TAGS" >> "$GITHUB_ENV"
          LABELS=($DOCKER_METADATA_OUTPUT_LABELS)
          LABELS=${LABELS[@]/#/--label }
          echo "LABELS=$LABELS" >> "$GITHUB_ENV"
      - name: Authenticate with registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - name: Install repo2docker
        run: pip install jupyter-repo2docker
      - name: Run repo2docker
        run: >
          jupyter-repo2docker
          --push
          --no-run
          --user-id 1000
          --user-name jovyan
          --subdir container
          --image-name $IMAGE_NAME
          --target-repo-dir /srv/container
          --appendix "$(< $PWD/container/appendix)"
          --DockerEngine.extra_buildx_build_args=--cache-from="type=registry,ref=$IMAGE_NAME:cache"
          --DockerEngine.extra_buildx_build_args=--cache-to="type=registry,ref=$IMAGE_NAME:cache,mode=max"
          $TAGS
          $LABELS
          $PWD
