name: Container image
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/container-image.yml
      - container/**
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    permissions:
      contents: read
      packages: write
    steps:
      - name: Export variables
        uses: actions/github-script@v8
        with:
          script: |
            const registry = process.env.REGISTRY
            const repo = process.env.GITHUB_REPOSITORY
            const hash = process.env.GITHUB_SHA.substring(0, 12)
            core.exportVariable('INPUT_IMAGE_NAME', `${registry}/${repo}`)
            core.exportVariable('SHA_NAME', `${registry}/${repo}:${hash}`)
      - name: Checkout container files
        uses: actions/checkout@v5
        with:
          sparse-checkout: container
      - name: Authenticate with registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - name: Install repo2docker
        run: pip install jupyter-repo2docker
      - name: Run repo2docker
        run: >
          jupyter-repo2docker
          --push
          --no-run
          --user-id 1000
          --user-name jovyan
          --subdir container
          --image-name ${SHA_NAME}
          --target-repo-dir /srv/container
          --appendix "$(< ${PWD}/container/appendix)"
          --label "repo2docker.ref=${GITHUB_REF}"
          --label "repo2docker.repo=https://github.com/${GITHUB_REPOSITORY}"
          --DockerEngine.extra_buildx_build_args="--cache-from=type=registry,ref=${INPUT_IMAGE_NAME}:buildcache"
          --DockerEngine.extra_buildx_build_args="--cache-to=type=registry,ref=${INPUT_IMAGE_NAME}:buildcache,mode=max"
          ${PWD}
