name: Preview website
on:
  push:
  pull_request:
    branches:
      - workflow
jobs:
  # call:
  #   uses: ./.github/workflows/build-website.yaml
  deploy:
    # # needs: call
    # permissions:
    #   pages: write
    #   id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # - name: Publish
      #   id: deployment
      #   uses: actions/deploy-pages@v4
      - name: Debug
        id: debug
        run: |
          echo $TEST
          
