name: Preview website
on:
  push:
jobs:
  call:
    if: ${{ github.repository_owner }} != 'nasa'
    uses: ./.github/workflows/build-website.yaml
    secrets: inherit
  deploy:
    needs: call
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ github.repository_owner }}
      # - name: Publish
      #   id: deployment
      #   uses: actions/deploy-pages@v4
